[package]
name = "odin_sandbox"
version = "0.1.0"
authors = ["BobbaMilkTea <btea7art@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
